### ISSUE TITLE
load existing weights and training

### ISSUE THREAD

**Issue by amardeepjaiman** [Oslandia/mapillary_classification#136]
Can someone tell me how to load the existing trained weights from some other dataset and use it to train the model on another datasst.(class is same) ?

**Comment by delhomer** [comment]
Hi @amardeepjaiman,

I'm not sure to understand your point. Are you interested in our trained models? In such a case, I suggest you to contact Oslandia directly by email! Otherwise, if you bring your own trained weights, transfer learning is certainly possible under the condition that the model architectures (the one which produced the weights, and ours) actually fit. As we use Keras, the weights are stored in `h5` files; such files may be handled in other contexts.

**Comment by delhomer** [comment]
No news, I close this issue.
